name: flutter_fiap_project2
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0" 

dependencies:
  flutter:
    sdk: flutter
  battery: ^1.0.7 
  cloud_firestore: ^0.14.3
  connectivity: ^2.0.2
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  firebase_functions_interop: ^1.0.2
  firebase_messaging: ^6.0.16
  flare_flutter: ^2.0.6
  flutter_mobx: ^1.1.0+1
  font_awesome_flutter: ^8.10.0
  get_it: ^5.0.3
  google_fonts: ^1.1.1
  google_maps_flutter: ^1.0.6
  http: ^0.12.2
  json_serializable: ^3.5.1
  mobx: ^1.2.1+1
  mobx_codegen: ^1.1.0+1
  path: null
  path_provider: ^1.6.24
  pedantic: ^1.9.2
  provider: ^4.3.1
  share: ^0.6.5+4
  sqflite: ^1.3.2+1
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2

flutter:

  uses-material-design: true
  assets:
    - assets/
